name: ninjaninja140-ts-template

services:
    app:
        image: ninjaninja140/ts-template
        container_name: ninjaninja140-ts-template
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
